### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by vkassingh** [rhythm98/Food-Ordering-Application#1]
I would like to contribute to the project as part of gssoc21. Do we have a discord group or similar for discussions?

**Comment by rhythm98** [comment]
PLEASE CONTACT BELOW persons for the same.
girlscriptsummerofcode21@gmail.com
mansibhardwaj009@gmail.com
gssoc@girlscript.tech
Hope this helps.

**Comment by shairanshrawat** [comment]
I am a participant of GSSOC 2021. I want to contribute to this issue and work on the same. Please could you assign me this issue as a part of GSSOC 2021.
Thank you.

**Comment by Ananya88** [comment]
Hey !!
I am interested in this project as GSSOC '21 participant .
And I would like to to update the Readme.md file by adding :

1.How to contribute in this project. The procedure from forking to making a pull request.
3.About how to add issues .
4. About the project.
Please assign me with this issue .Thanks.

**Comment by Riya764** [comment]
I am a GSSOC 21 participant and would like to work on this project

**Comment by sanyadeveloper2000** [comment]
Hey , I have expereince in technical writing. I think I would like to contribute to this issue.
Thank you

**Comment by vismitap** [comment]
May I work on this issue as a part of GSSoC?
