### ISSUE TITLE
 Error: Cannot find module 'sequelize/types'

### ISSUE THREAD

**Issue by anhushree** [rhythm98/Food-Ordering-Application#18]
### **Describe the bug:**
After the command `npm install`, the `npm start` throws an error saying `Cannot find module 'sequelize/types'`.

### **To Reproduce:**
1. Clone Repo
2. `npm install`
3. `npm start`
4.  `Error: Cannot find module 'sequelize/types'`
### **Expected behavior:**
I expected the `npm start` command to start the server `localhost://3000`.

### **Screenshots:**
![image](https://user-images.githubusercontent.com/56672958/114344758-05c65280-9b7e-11eb-9ec5-637777d50eb4.png)

<hr/>

**Comment by samridhikots** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by anhushree** [comment]
@sourabhsingh282 could you please tell me what to do next? This happened when I tried to run the program locally
