### ISSUE TITLE
Need to update the topic section

### ISSUE THREAD

**Issue by abhay27chauhan** [rhythm98/Food-Ordering-Application#4]
this application is not using reactjs for frontend. So need to remove reactjs from topic section of repo

**Comment by akshatvirmani** [comment]
I would like to work on this issue. Please assign this to me.

**Comment by ShambhaviSharma0110** [comment]
Hey, I'm interested in this project could you please allow me to work on it? I know a bit of react.js I can contribute

**Comment by abhay27chauhan** [comment]
@falguniraina I cannot update is because it is your repo. You have to update it by yourself in the topic section
